### ISSUE TITLE
[FEATURE] - Add new wallpaper

### ISSUE THREAD

**Issue by AadilRayeen** [tcet-opensource/tcet-linux-wallpaper#17]
### Describe the improvement

- Add more wallpaper for TCET_Linux

### Why do we need this?

It will give more wallpaper options to TCET-Linux users.

### Do you have a proposed solution?

- Made a wallpaper to enhance the desktop view of TCET Linux Users.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

### Terms and Conditions

- [X] I agree to follow this project's Code of Conduct

**Comment by AadilRayeen** [comment]
@Akash6222 @harshau007 @beans9926 please assign this issue to me

**Comment by harshau007** [comment]
> @Akash6222 @harshau007 @beans9926 please assign this issue to me 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Done 👍

**Comment by AadilRayeen** [comment]
@Akash6222 @beans9926 @harshau007 kindly review
